
name: interrogate
channels:
  - conda-forge

dependencies:
  - altair
  - black
  - numba
  - numpy
  - pandas
  - pip
  - pydeck
  - python
  - safety
  - scikit-learn
  - streamlit
  - xgboost
  - pip:
